import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Work from '@/components/Work/Work'
import Coursework from '@/components/Coursework/Coursework'
import Reviews from '@/components/Reviews/Reviews'
import CourseworkOther from '@/components/CourseworkOther/CourseworkOther'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Coursework/>
      <Reviews/>
      <CourseworkOther/>
    </>
  )
}
